### ISSUE TITLE
Notification says I'm not connected

### ISSUE THREAD

**Issue by ghost** [jcjordyn130/simpleirc#9]
1.7 release notes said "Removed a line from IRCService.java that was causing Simple IRC to think it was disconnected all the time"

But I'm using 1.8 and the notification still says "Not connected" instead of "Simple IRC is running" after a while, even though I'm still connected.

**Comment by jcjordyn130** [comment]
Fixed in commit 7c2826d273b3c4253aa7e8ddfff68b8e3a35223b and Version 1.9 :)

**Comment by ghost** [comment]
It's still happening on my end.

Link removed by jcjordyn130 (Mod note: don't ever do that again.)
https://puu.sh/t80Jw/32f887b537.JPG

**Comment by jcjordyn130** [comment]
@T7000 try uninstalling it then installing it again.

**Comment by kozross** [comment]
I just got this exact issue - was on 1.9 from the very beginning. Also, the notification is not dismissable.
